add|app|Admin|C:\PM\dist\pm-admin-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.admin.PmAdmin|Admin >> |[CLIENT_COMPUTER_NAME]
add|app|Rich Text Editor|C:\PM\dist\pm-app-rtf-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.rtf.RTFEditor|RTF Editor >> |[CLIENT_COMPUTER_NAME]
add|app|Workflow Editor|C:\PM\dist\pm-app-wkf-pdf-1.5.jar;C:\PM\dist\pm-app-pdf-view-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.workflow.WorkflowPDF|Workflow Editor >>|[CLIENT_COMPUTER_NAME]
add|app|PDF Viewer|C:\PM\dist\pm-app-pdf-view-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.pdfviewer.PDFViewer|PDF Viewer >> |[CLIENT_COMPUTER_NAME]
add|app|e-grant|C:\PM\dist\pm-app-grant-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.grantor.Grantor|e-grant >> |[CLIENT_COMPUTER_NAME]
add|app|Exporter|C:\PM\dist\pm-exporter-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.exporter.Exporter|Exporter >> |[CLIENT_COMPUTER_NAME]
add|app|Open Office|C:\PM\dist\pm-app-openoffice-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar;C:\Program Files (x86)\OpenOffice.org 3\Basis\program\classes\unoil.jar;C:\Program Files (x86)\OpenOffice.org 3\URE\java\juh.jar;C:\Program Files (x86)\OpenOffice.org 3\URE\java\jurt.jar;C:\Program Files (x86)\OpenOffice.org 3\URE\java\ridl.jar;C:\Program Files (x86)\OpenOffice.org 3\program|gov.nist.csd.pm.application.openoffice.OfficeLauncher|Open Office >>|[CLIENT_COMPUTER_NAME]
add|app|Microsoft Office Launcher|C:\PM\dist\pm-app-msoffice-1.5.jar|gov.nist.csd.pm.application.office.MSOfficeLauncher|MS Office >>|[CLIENT_COMPUTER_NAME]
add|app|Med-Rec|C:\PM\dist\pm-app-medrec-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.medrec.MREditor|Med-Rec >>|[CLIENT_COMPUTER_NAME]
add|app|Acct-Rec|C:\PM\dist\pm-app-acctrec-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.acctrec.AcctEditor|Acct-Rec >>|[CLIENT_COMPUTER_NAME]
add|app|Workflow Old|C:\PM\dist\pm-app-wkf-old-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.oldworkflow.Wkflow|Workflow Old >>|[CLIENT_COMPUTER_NAME]
add|app|Schema Builder|C:\PM\dist\pm-app-schemabuilder-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.appeditor.SchemaBuilder3|SB>>|[CLIENT_COMPUTER_NAME]
add|app|Employee Record|C:\PM\dist\pm-app-emprec-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.appeditor.EmployeeRecord|ER>>|[CLIENT_COMPUTER_NAME]
add|app|Table Editor|C:\PM\dist\pm-app-tableeditor-1.5.jar;C:\PM\dist\pm-commons-1.5.jar;C:\PM\lib\activation-1.1.jar;C:\PM\lib\aopalliance-1.0.jar;C:\PM\lib\asm-3.1.jar;C:\PM\lib\bcmail-jdk15-1.44.jar;C:\PM\lib\bcprov-jdk15-1.44.jar;C:\PM\lib\cglib-2.2.1-v20090111.jar;C:\PM\lib\colorchooser-1.0.jar;C:\PM\lib\commons-logging-1.1.1.jar;C:\PM\lib\fontbox-1.6.0.jar;C:\PM\lib\guava-r09.jar;C:\PM\lib\guice-3.0.jar;C:\PM\lib\icu4j-3.8.jar;C:\PM\lib\jarjar-1.0.jar;C:\PM\lib\javax.inject-1.jar;C:\PM\lib\javax.mail-1.4.4.jar;C:\PM\lib\jempbox-1.6.0.jar;C:\PM\lib\jfontchooser-1.0.5-pm.jar;C:\PM\lib\jna-3.2.7-pm-platform.jar;C:\PM\lib\jna-3.2.7-pm.jar;C:\PM\lib\jsr305-1.3.7.jar;C:\PM\lib\miglayout-3.7.3.1-swing.jar;C:\PM\lib\pdfbox-1.6.0.jar;C:\PM\lib\wrapper-3.2.3.jar;C:\PM\lib\wrapper.jar|gov.nist.csd.pm.application.appeditor.TableEditor|TE>>|[CLIENT_COMPUTER_NAME]

add|ks|C:\PM\keystores\superKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|super

add|ks|C:\PM\keystores\aliceKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|alice

add|ks|C:\PM\keystores\katieKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|katie

add|ks|C:\PM\keystores\daveKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|dave

add|ks|C:\PM\keystores\bobKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|bob

add|ks|C:\PM\keystores\charlieKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|charlie

add|ks|C:\PM\keystores\exporterKeystore|C:\PM\keystores\clientTruststore|h|[CLIENT_COMPUTER_NAME]|u|exporter



